"""Build the browser route worker from the same engine and policy used in training."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser()
parser.add_argument('--weights15',required=True)
args=parser.parse_args()
weights=json.loads(Path(args.weights15).read_text())
html=(ROOT/'grid-clash/index.html').read_text(encoding='utf-8')
script=html.split('<script>')[1].split('</script>')[0]
core=script[script.index('const C='):script.index('const boardbox=')]
teacher=(ROOT/'training/teacher.js').read_text(encoding='utf-8')
route=teacher[:teacher.index('function teacherSnapshot')]
proposal=teacher[teacher.index('function teacherProposal'):teacher.index('function teacherChoose')]
body='let requestedSize=15;\n'+core+'\nlet originalAI=aiDirection;const originalTarget=chooseNewTarget;\n'+route+proposal+'''
return function advise(state,player,weights){
  n=state.board.length;
  if(n!==15||state.players.length!==3)throw new Error('Route v2 supports 15x15 / 3 players');
  g=state.board.map(row=>row.slice());
  a=state.players.map(p=>({...p,h:false,strategy:'apex',commit:null,enclosurePlan:null,
    planBlocked:0,noGain:0,panic:0,visits:new Map(),recent:[],blocked:new Map(),
    loopPlan:[],loopPos:0,loopCooldown:0,atlasEscape:false,atlasTarget:null,atlasAvoid:null}));
  a[player]=structuredClone(state.own[player]);a[player].strategy='candidate';
  candidateWeights=weights;turn=state.turn;occ=state.occ;run=true;ended=false;
  temporaryBlocks=new Set(state.blocks);globalPanic=state.globalPanic;
  stateSeen=new Map(state.stateSeen);idleAttempts=state.idleAttempts;tailHistory=state.tailHistory;
  const p=a[player];
  const initial=turn===0&&occ===a.length&&idleAttempts===0&&a.every(q=>{
    const angle=-Math.PI/2+Math.PI*2*q.id/a.length;
    return q.x===Math.round((n-1)/2+Math.cos(angle)*n*.36)&&q.y===Math.round((n-1)/2+Math.sin(angle)*n*.36);
  });
  if(initial&&weights.openings?.[player]){
    p.loopPlan=weights.openings[player].plan.slice();p.loopPos=0;
  }
  const action=canExpand(p)?teacherProposal(p):null;
  p.strategy='atlas';
  return {action,memory:p};
};
'''
worker='''// Generated by training/build_route_worker.py; do not edit by hand.
// Pure local route planning. No network, ONNX runtime, or opponent private plans.
const elements=new Map();
const document={querySelector(selector){
  if(!elements.has(selector))elements.set(selector,{value:'3',checked:false,style:{},
    classList:{remove(){},toggle(){},add(){}},getContext:()=>({}),getBoundingClientRect:()=>({width:0})});
  return elements.get(selector);
}};
let randomSeed=101;
const policyMath=Object.create(Math);
policyMath.random=()=>{randomSeed=(Math.imul(randomSeed,1664525)+1013904223)>>>0;return randomSeed/4294967296;};
'''
worker+='const routeWeights='+json.dumps(weights,separators=(',',':'))+';\n'
worker+='const advise=new Function("document","Math",'+json.dumps(body)+')(document,policyMath);\n'
worker+='''self.onmessage=({data})=>{
  try{
    const decisions={};
    for(const player of data.players){
      randomSeed=101+data.state.turn*31+player*65537;
      decisions[player]=advise(data.state,player,routeWeights);
    }
    self.postMessage({id:data.id,decisions});
  }catch(error){self.postMessage({id:data.id,error:String(error.stack||error)});}
};
'''
(ROOT/'grid-clash/route-worker.js').write_text(worker,encoding='utf-8',newline='\n')
manifest=dict(name='ATLAS-R Route v2',size=15,count=3,method='trained_route_parameters_and_short_opening',
              weights=weights,worker_sha256=hashlib.sha256(worker.encode()).hexdigest(),
              source_sha256=hashlib.sha256((core+route+proposal).encode()).hexdigest(),release_approved=False,
              release_channel='experimental',experimental_publish_authorized=True)
(ROOT/'grid-clash/atlas-route-v2.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
print(json.dumps(dict(worker_bytes=len(worker.encode()),**{k:v for k,v in manifest.items() if k!='weights'})))
